#! /bin/bash

set -e

if [ "$1" != "-d" ]; then
    echo "Read the souce Luke."
    exit 1
fi

gen_testset() {
    rm -rf debs
    mkdir -p debs
    ./deb-generator -o ./debs -n test-ws-1.0 -v 0.1.0SNAPSHOT -r 1111
    ./deb-generator -o ./debs -n test-ws-1.0 -v 0.1.0SNAPSHOT -r 2222
    ./deb-generator -o ./debs -n test-ws-1.0 -v 0.1.0SNAPSHOT -r 3333
    ./deb-generator -o ./debs -n testtool -v 1.3.0 -r 23
    ./deb-generator -o ./debs -n testupdate -v 2.0 -r 1
    ./deb-generator -o ./debs -n testupdate -v 2.1 -r 1
}

gen_repoidx() {
    cd debs
    dpkg-scanpackages -m . >Packages
    touch Sources

    apt-ftparchive release . > Release
    gpg --sign -ba --output Release.gpg Release
    gpg --export --armor ABE162687810FA71 | sudo apt-key add -
}

add_repo() {
    sudo apt-add-repository "deb file:$(pwd)/ ./"
}

# ruby1.9.1 -r webrick -e "s = WEBrick::HTTPServer.new(:Port => 9090, :DocumentRoot => Dir.pwd); trap('INT') { s.shutdown }; s.start"

gen_testset
gen_repoidx
add_repo
